version: '3.8'
services:
  nestapp:
    build: ./
    ports:
      - "3001:3000"
    env_file:
      - .env  
    depends_on:
      - postgresdb  
    networks:
      - nestnetwork  

  postgresdb:
    image: postgres
    volumes: 
      - pgdata:/var.lib/postgresql/data
    env_file: 
      - .env
    networks:
      - nestnetwork  


networks:
  nestnetwork:
    driver: bridge


volumes:
  pgdata:
      
